version: "3.9"
services:
  backend:
    image: backend
    build:
      context: ./django
    volumes:
      #- ./django/db.sqlite3:/django/db.sqlite3
      - files:/django/files
    environment:
      - SECRET_KEY=django-insecure-32&bz99#@)bwix0ddn#^tcu%uo2&*gl=rtivx$t_^bp9%e%_8*
    command: daphne -b 0.0.0.0 -p 8000 diploma.asgi:application
    #command: python manage.py runserver 0.0.0.0:8000
  nginx:
    image: nginx
    build:
      context: ./react-ui
    ports:
      - 80:8080
    depends_on:
      - backend
volumes:
  files:
  #db.sqlite3: