# Generated by Django 4.0.4 on 2022-06-23 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=64)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('content_type', models.CharField(blank=True, default='', max_length=254)),
                ('file_name', models.CharField(blank=True, default='', max_length=254)),
                ('file_size', models.PositiveBigIntegerField(blank=True, default=0)),
                ('file_width', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('file_height', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('file_fps', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('file_numframes', models.PositiveBigIntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
